# main:
#   - name: nav.blogs
#     pageRef: /blogs
#     weight: 20
#     params:
#       icon: posts
#   - name: nav.projects
#     pageRef: /projects
#     weight: 25
#     params:
#       icon: projects
#   - name: nav.guides
#     pageRef: /guides
#     weight: 30
#     params:
#       icon: categories

main:
  - name: nav.posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - name: nav.projects
    pageRef: /projects
    weight: 25
    params:
      icon: projects
  - name: nav.categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories
  - name: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - name: nav.archives
    pageRef: /archives
    weight: 50
    params:
      icon: archive