main:
  - name: Projects
    pageRef: /projects
    weight: 19
    params:
      icon: projects
  - name: Blogs
    pageRef: /blogs
    weight: 20
    params:
      icon: posts


# footer with links
# TODO: Update URLs
social:
  - name: GitHub
    url: https://github.com/sebs-commits
    weight: 10
    params:
      icon: github
  - name: LinkedIn
    url: https://www.linkedin.com/in/sebastian-d-3ab39119b
    weight: 20
    params:
      icon: linkedin
  - name: Email
    url: mailto:contact@sebdavid.com"
    weight: 30
    params:
      icon: email